services:
  frontend:
    build:
      context: ../m-motors-frontend
    container_name: m-motors-frontend
    volumes:
      - /app/node_modules  # Save node_modules for Avoid conflicts with dependencies
    ports:
      - "3000:3000"
